from tkinter import *
Kartikey = Tk()
# Kartikey.geometry("1500x700")
# Kartikey.resizable(0,0)
Kartikey.title('MOVIE RECOMMENDATION SYSTEM')
se = PhotoImage(file=r"C:\Users\ASUS\Downloads\png.png")
bg = PhotoImage(file=r"C:\Users\ASUS\Downloads\narutooo.png")
fe = PhotoImage(file=r"C:\Users\ASUS\Downloads\MOVIE RECOMMENDATION SYSTEM1.png")
backg = Canvas(Kartikey)
Search=Frame(backg,bg = "GREY12")
f1 = Frame(backg)
Toprated = Canvas(f1,height = 350,width = 1000,bg = "BLACK")
Recommend = Frame(backg)


img1 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (2).png")
img2 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (1).png")
img3 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (3).png")
img4 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (4).png")
img5 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (5).png")
img6 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (6).png")
img7 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (7).png")
img8 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (8).png")
img9 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (9).png")
img10 = PhotoImage(file = r"C:\Users\ASUS\Downloads\Sys\1 (10).png")


Toprated.create_image(200,100,image = img1)
Toprated.create_image(450,100,image = img2)
Toprated.create_image(700,100,image = img3)
Toprated.create_image(950,100,image = img4)
Toprated.create_image(1200,100,image = img5)
Toprated.create_image(1450,100,image = img6)
Toprated.create_image(1700,100,image = img7)
Toprated.create_image(1950,100,image = img8)
Toprated.create_image(2200,100,image = img9)
Toprated.create_image(2450,100,image = img10)

Toprated.pack()

scroll_x = Scrollbar(f1, orient="horizontal", command=Toprated.xview)
scroll_x.pack(fill = "x")

Toprated.configure(xscrollcommand=scroll_x.set)
Toprated.configure(scrollregion=Toprated.bbox("all"))
ser=StringVar()
Label(Search,text="SEARCH : ",bg="GREY12",fg="#ffffff",font=" 25 ").grid(row=0,column=0)
Entry(Search,bg = "GREY5",textvariable=ser,fg="WHITE").grid(row=0,column=1)
Button(Search,image=se,borderwidth=0,bg = "GREY12",activebackground="GREY").grid(row=0,column=2,padx=(20, 0))

backg.create_image(0,0,image = bg,anchor = NW)
backg.create_image(150,100,image = fe)
backg.create_window(1300,50,window = Search)
backg.create_window(780,350,window = f1)
backg.create_window(780,700,window = Recommend)
backg.pack(fill = "both",expand = True)
backg.config(bg = "GREY12")

Kartikey.mainloop()
